### ISSUE TITLE
Problem with python examples

### ISSUE THREAD

**Issue by rougier** [alexrockhill/pd-parser#1]
I've installed the latest version and tried to run the two examples from https://alexrockhill.github.io/pd-parser/auto_examples/index.html but it failed. Not sure about the exact reason (missing data?)

```
$ python plot_find_pd_events.py

Creating RawArray with float64 data, n_channels=1, n_times=2044106
    Range : 0 ... 2044105 =      0.000 ...  2044.105 secs
Ready.
Traceback (most recent call last):
  File "plot_find_pd_events.py", line 33, in <module>
    raw, beh_df, events, corrupted_indices = \
ValueError: not enough values to unpack (expected 4, got 2)
```

```
$ python plot_find_pd_on_and_off.py

  File "plot_find_pd_on_and_off.py", line 40, in <module>
    pd_parser.simulate_pd_data(n_events=n_events, n_secs_on=n_secs_on,
TypeError: simulate_pd_data() got an unexpected keyword argument 'n_secs_on'
```

**Comment by alexrockhill** [comment]
Sorry the examples are unfortunately not backward compatible and don't work with the latest stable version, only the development version. I'll make a new release but in the meantime, you can run `pip install git+https://github.com/alexrockhill/pd-parser.git`to install the development version but I'll work on adding legacy documentation so this problem doesn't happen again also.

**Comment by rougier** [comment]
Thanks. I thought I posted a second issue but I cannot find it. I now got:

```
Used Annotations descriptions: ['Fixation', 'Go Cue', 'Response']
/usr/local/lib/python3.8/site-packages/pd_parser/parse_pd.py:879: RuntimeWarning: The unit for channel(s) pd has changed from V to NA.
  raw.set_channel_types({ch: 'stim' for ch in pd_channels
Traceback (most recent call last):
  File "plot_find_pd_events.py", line 127, in <module>
    pd_parser.pd_parser_save_to_bids(op.join(out_dir, 'bids_dir'), fname,
  File "/usr/local/lib/python3.8/site-packages/pd_parser/parse_pd.py", line 881, in pd_parser_save_to_bids
    bids_path = mne_bids.BIDSPath(subject=sub, session=ses, task=task,
AttributeError: module 'mne_bids' has no attribute 'BIDSPath'
```

**Comment by alexrockhill** [comment]
Ah, yeah the bleeding edge mne-bids release is used and it's in requirements.txt but not the setup.py dependencies. I'll add to install the requirements (`pip install -r requirements.txt`) until the next `mne-bids` release.

**Comment by rougier** [comment]
Ok. tell me when it's done such that I can test reinstall with pip.

**Comment by alexrockhill** [comment]
I changed the README and documentation to say that you need to pip install the bleeding edge mne-bids after pip installing pd-parser. I can update pypi too though I'll let you know when I've done that

**Comment by rougier** [comment]
That did the trick. Now for the second example, I got:
```
Traceback (most recent call last):
  File "plot_find_pd_on_and_off.py", line 80, in <module>
    pd_parser.add_pd_off_event(fname, off_event_name='Stim Off')
AttributeError: module 'pd_parser' has no attribute 'add_pd_off_event'
```

**Comment by alexrockhill** [comment]
It looks like I'd have to release a new version so I think I'll just have to leave it as just the documentation changed re the last issue.

Looking at the most recent traceback now.

**Comment by alexrockhill** [comment]
It's ``add_pd_off_events`` not ``add_pd_off_event``, I thought I tested but I should have done better. I will be fixed momentarily.

**Comment by alexrockhill** [comment]
The example documentation is fixed now, thanks for catching that.
