### ISSUE TITLE
Provide developer test instructions

### ISSUE THREAD

**Issue by rly** [alexrockhill/pd-parser#2]
There should be documentation on how to run automated tests.
https://joss.readthedocs.io/en/latest/review_criteria.html#tests

Note that one of the tests requires `bids-validator`. It looks like that needs to be installed globally via `npm 
install -g bids-validator` (`pip install bids-validator` did not install an executable, at least on my system). 

Example documentation:

- Run `pip install pytest`
- Install Node.js (at least version 10.11.0)
- Run `npm install -g bids-validator`
- Run `pytest`

**Comment by alexrockhill** [comment]
Ok addressed in 3271d5ab88c08e1e03ad045b9b1f8f5be09f260e, it's very similar to the `mne-bids` testing as that's where the validator tests are from.

**Comment by rly** [comment]
Looks good.
