### ISSUE TITLE
Provide contributor guidelines

### ISSUE THREAD

**Issue by rly** [alexrockhill/pd-parser#3]
There should be clear guidelines for third-parties wishing to:
- Contribute to the software
- Report issues or problems with the software
- Seek support

https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines

This is missing.

**Comment by alexrockhill** [comment]
Hmm okay, I did it similar to other projects for the contributing guidelines but I didn't really include anywhere to seek support besides the issue tracker 5462da8d081883b26e1b8e81a65e47a7aa2ef253. I think that's okay for now by me but maybe I will make a Gitter or something soon unless you'd suggest doing that now.

**Comment by rly** [comment]
I think the GitHub issue tracker is sufficient for seeking support. Looks good.
