### ISSUE TITLE
Clarification to README.rst

### ISSUE THREAD

**Issue by libertyh** [alexrockhill/pd-parser#6]
As a quick clarification for those looking for download the examples, I suggest that the README.rst be changed to reflect that the Examples page is part of the Documentation page (and not within the examples directory within the git repo, for example). For example, in "Getting Started", the following text could have a link to https://alexrockhill.github.io/pd-parser/auto_examples/index.html . 

> In the 'Examples' page, click on 'Download all examples in Jupyter notebooks'

**Comment by alexrockhill** [comment]
Good suggestion, I've added it in the latest commit ba121ae165977c61f754ca7fe8ed63e51c9f73b5.

It's only in the development documentation for now but it will be in the stable documentation soon when the next version release happens.

**Comment by alexrockhill** [comment]
It is in the README now though too.

I wouldn't want someone to try to use it for the first time and hit a roadblock there though... actually I'm changing the version 0.2 documentation too now, great point

**Comment by libertyh** [comment]
It looks like this Examples page link isn't working anymore in the README, maybe because of the new docs release? If you can fix that I can close this issue.

**Comment by alexrockhill** [comment]
Oops typo in the html, it's fixed with the latest commit
